import "./App.css";
import React, { useState } from "react";
import { Outlet } from "react-router-dom";
import { v4 as uuid } from "uuid";
import NavBar from "./components/NavBar";
import SideBar from "./components/SideBar";

const moviesData = [
  {
    id: uuid(),
    title: "Jurassic Park",
    year: 1993,
    director: "Steven Spielberg",
    genre: "Sci-Fi, Adventure",
    rating: 8.1,
    runtime: 127,
    actors: [
      "Sam Neill",
      "Laura Dern",
      "Jeff Goldblum",
      "Richard Attenborough",
      "Bob Peck",
    ],
    plot: "During a preview tour, a theme park suffers a major power breakdown that allows its cloned dinosaur exhibits to run amok.",
    src: "https://tse3.mm.bing.net/th?id=OIP.WR_xNPwmiPwaDpTnUIuiMwHaLZ&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "Fury",
    year: 2014,
    director: "David Ayer",
    genre: "Action, Drama, War",
    rating: 7.6,
    runtime: 134,
    actors: [
      "Brad Pitt",
      "Shia LaBeouf",
      "Logan Lerman",
      "Michael Peña",
      "Jon Bernthal",
    ],
    plot: "In the waning days of World War II, a battle-hardened U.S. Army sergeant named 'Wardaddy' commands a tank and his five-man crew on a deadly mission behind enemy lines.",
    src: "https://tse3.mm.bing.net/th?id=OIP.KkNNDBTUCHSl55bbL3HNtAHaK-&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "The Avengers",
    year: 2012,
    director: "Joss Whedon",
    genre: "Action",
    rating: 8.0,
    runtime: 143,
    actors: [
      "Robert Downey Jr.",
      "Chris Evans",
      "Mark Ruffalo",
      "Chris Hemsworth",
      "Scarlett Johansson",
    ],
    plot: "Earth's mightiest heroes must come together and learn to fight as a team to stop the mischievous Loki and his alien army from enslaving humanity.",
    src: "https://tse3.mm.bing.net/th?id=OIP.iAsDFqwmY2RZZVAt9kiojwHaLH&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "The Dark Knight",
    year: 2008,
    director: "Christopher Nolan",
    genre: "Action, Crime, Drama",
    rating: 9.0,
    runtime: 152,
    actors: [
      "Christian Bale",
      "Heath Ledger",
      "Michael Caine",
      "Gary Oldman",
      "Morgan Freeman",
    ],
    plot: "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
    src: "https://tse4.mm.bing.net/th?id=OIP.NN9rKH-vZbFgtH4FuoW7OwHaLH&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "Men in Black",
    year: 1997,
    director: "Barry Sonnenfeld",
    genre: "Action, Comedy, Sci-Fi",
    rating: 7.3,
    runtime: 98,
    actors: [
      "Will Smith",
      "Tommy Lee Jones",
      "Linda Fiorentino",
      "Vincent D'Onofrio",
      "Rip Torn",
    ],
    plot: "A police officer joins a secret organization that polices and monitors extraterrestrial interactions on Earth.",
    src: "https://tse3.mm.bing.net/th?id=OIP.BWNJ5PRQjuhMkJwJFxRJ1QHaLH&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "Inception",
    year: 2010,
    director: "Christopher Nolan",
    genre: "Action, Adventure, Sci-Fi",
    rating: 8.8,
    runtime: 148,
    actors: [
      "Leonardo DiCaprio",
      "Joseph Gordon-Levitt",
      "Elliot Page",
      "Tom Hardy",
      "Ken Watanabe",
    ],
    plot: "A thief, who steals corporate secrets through the use of dream-sharing technology, is given the inverse task of planting an idea into the mind of a CEO.",
    src: "https://tse3.mm.bing.net/th?id=OIP.SDeJ32DZYc-p3O_6N1z2gAHaKz&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "Pulp Fiction",
    year: 1994,
    director: "Quentin Tarantino",
    genre: "Crime, Drama",
    rating: 8.9,
    runtime: 154,
    actors: [
      "John Travolta",
      "Samuel L. Jackson",
      "Uma Thurman",
      "Bruce Willis",
      "Ving Rhames",
    ],
    plot: "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
    src: "https://tse4.mm.bing.net/th?id=OIP.3nvyOkddyFma1o0Ulrs4BgHaLH&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "The Shawshank Redemption",
    year: 1994,
    director: "Frank Darabont",
    genre: "Drama",
    rating: 9.3,
    runtime: 142,
    actors: [
      "Tim Robbins",
      "Morgan Freeman",
      "Bob Gunton",
      "William Sadler",
      "Clancy Brown",
    ],
    plot: "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
    src: "https://tse1.mm.bing.net/th?id=OIP.ZdssOf9KzSHlVRLaJqnK1wHaLH&pid=Api&P=0&h=180",
  },
  // Additional movie recommendations
  {
    id: uuid(),
    title: "A Bronx Tale",
    year: 1993,
    director: "Robert De Niro",
    genre: "Crime, Drama",
    rating: 7.8,
    runtime: 121,
    actors: [
      "Robert De Niro",
      "Chazz Palminteri",
      "Lillo Brancato",
      "Francis Capra",
      "Taral Hicks",
    ],
    plot: "A young boy grows up in the Bronx under the guidance of his hardworking father and the influence of a local mob boss.",
    src: "https://tse4.mm.bing.net/th?id=OIP.y4ENZThKa-urySNhpw-VagHaLH&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "Robin Hood: Prince of Thieves",
    year: 1991,
    director: "Kevin Reynolds",
    genre: "Action, Adventure, Drama",
    rating: 6.9,
    runtime: 143,
    actors: [
      "Kevin Costner",
      "Morgan Freeman",
      "Mary Elizabeth Mastrantonio",
      "Christian Slater",
      "Alan Rickman",
    ],
    plot: "When Robin and his Moorish companion come to England and the tyranny of the Sheriff of Nottingham, he decides to fight back as an outlaw.",
    src: "https://tse1.mm.bing.net/th?id=OIP.XdxJs8ZuC4c3KgGx6mnr9gHaJ4&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "The Prestige",
    year: 2006,
    director: "Christopher Nolan",
    genre: "Drama, Mystery, Sci-Fi",
    rating: 8.5,
    runtime: 130,
    actors: [
      "Christian Bale",
      "Hugh Jackman",
      "Scarlett Johansson",
      "Michael Caine",
      "David Bowie",
    ],
    plot: "Two magicians engage in a competitive rivalry, leading to a series of dangerous illusions and personal sacrifices.",
    src: "https://tse1.mm.bing.net/th?id=OIP.YsSPTmPlu6l5vTixMWuXsQHaIl&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "The Departed",
    year: 2006,
    director: "Martin Scorsese",
    genre: "Crime, Drama, Thriller",
    rating: 8.5,
    runtime: 151,
    actors: [
      "Leonardo DiCaprio",
      "Matt Damon",
      "Jack Nicholson",
      "Mark Wahlberg",
      "Martin Sheen",
    ],
    plot: "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in South Boston.",
    src: "https://tse3.mm.bing.net/th?id=OIP.v-d7uAsU9JzCbRuRTr5KEAHaLH&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "The Revenant",
    year: 2015,
    director: "Alejandro G. Iñárritu",
    genre: "Adventure, Drama, Thriller",
    rating: 8.0,
    runtime: 156,
    actors: [
      "Leonardo DiCaprio",
      "Tom Hardy",
      "Domhnall Gleeson",
      "Will Poulter",
      "Forrest Goodluck",
    ],
    plot: "A frontiersman on a fur trading expedition fights for survival after being mauled by a bear and left for dead by his hunting team.",
    src: "https://tse4.mm.bing.net/th?id=OIP.JmwEZ89Szh_Xt55627uBsAHaJ4&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "Blade Runner 2049",
    year: 2017,
    director: "Denis Villeneuve",
    genre: "Action, Drama, Mystery",
    rating: 8.0,
    runtime: 164,
    actors: [
      "Ryan Gosling",
      "Harrison Ford",
      "Ana de Armas",
      "Sylvia Hoeks",
      "Robin Wright",
    ],
    plot: "A young blade runner's discovery of a long-buried secret leads him to track down former blade runner Rick Deckard, who's been missing for thirty years.",
    src: "https://tse3.mm.bing.net/th?id=OIP.Ng6U-9RjEdbimMwczbZWKgHaLH&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "Mad Max: Fury Road",
    year: 2015,
    director: "George Miller",
    genre: "Action, Adventure, Sci-Fi",
    rating: 8.1,
    runtime: 120,
    actors: [
      "Tom Hardy",
      "Charlize Theron",
      "Nicholas Hoult",
      "Zoë Kravitz",
      "Rosie Huntington-Whiteley",
    ],
    plot: "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search of her homeland with the help of a group of female prisoners, a psychotic worshipper, and a drifter named Max.",
    src: "https://tse1.explicit.bing.net/th?id=OIP.aZdKkTtYotxYc3qyztOROwHaLH&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "The Godfather",
    year: 1972,
    director: "Francis Ford Coppola",
    genre: "Crime, Drama",
    rating: 9.2,
    runtime: 175,
    actors: [
      "Marlon Brando",
      "Al Pacino",
      "James Caan",
      "Robert Duvall",
      "Diane Keaton",
    ],
    plot: "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
    src: "https://tse4.explicit.bing.net/th?id=OIP.u5lvdFqa0C_9hkIh5t47XgHaLH&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "Fight Club",
    year: 1999,
    director: "David Fincher",
    genre: "Drama",
    rating: 8.8,
    runtime: 139,
    actors: [
      "Brad Pitt",
      "Edward Norton",
      "Helena Bonham Carter",
      "Meat Loaf",
      "Jared Leto",
    ],
    plot: "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
    src: "https://tse2.mm.bing.net/th?id=OIP.X8GXwUnJEzAclGg3OtAnrAHaLH&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "Romeo + Juliet",
    year: 1996,
    director: "Baz Luhrmann",
    genre: "Drama, Romance",
    rating: 6.7,
    runtime: 120,
    actors: [
      "Leonardo DiCaprio",
      "Claire Danes",
      "John Leguizamo",
      "Harold Perrineau",
      "Pete Postlethwaite",
    ],
    plot: "Shakespeare's famous play is updated to the hip modern suburb of Verona Beach, where Romeo and Juliet fall in love and secretly wed, against their parents' wishes.",
    src: "https://tse3.mm.bing.net/th?id=OIP.AnpGuP4ImB3sl6gkinK_9AAAAA&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "Goodfellas",
    year: 1990,
    director: "Martin Scorsese",
    genre: "Biography, Crime, Drama",
    rating: 8.7,
    runtime: 146,
    actors: [
      "Robert De Niro",
      "Ray Liotta",
      "Joe Pesci",
      "Lorraine Bracco",
      "Paul Sorvino",
    ],
    plot: "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.",
    src: "https://tse3.mm.bing.net/th?id=OIP.FIq0THTKf-TURbBiKYSyTAHaLH&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "The Matrix",
    year: 1999,
    director: "Lana Wachowski, Lilly Wachowski",
    genre: "Action, Sci-Fi",
    rating: 8.7,
    runtime: 136,
    actors: [
      "Keanu Reeves",
      "Laurence Fishburne",
      "Carrie-Anne Moss",
      "Hugo Weaving",
      "Joe Pantoliano",
    ],
    plot: "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
    src: "https://tse3.mm.bing.net/th?id=OIP.mCr3x90hubrByxx2xp21EwHaLH&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "Interstellar",
    year: 2014,
    director: "Christopher Nolan",
    genre: "Adventure, Drama, Sci-Fi",
    rating: 8.6,
    runtime: 169,
    actors: [
      "Matthew McConaughey",
      "Anne Hathaway",
      "Jessica Chastain",
      "Michael Caine",
      "Matt Damon",
    ],
    plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    src: "https://tse4.mm.bing.net/th?id=OIP.eWSrCr-OPPb6owngrN_V5QHaLH&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "The Silence of the Lambs",
    year: 1991,
    director: "Jonathan Demme",
    genre: "Crime, Drama, Thriller",
    rating: 8.6,
    runtime: 118,
    actors: [
      "Jodie Foster",
      "Anthony Hopkins",
      "Lawrence A. Bonney",
      "Kasi Lemmons",
      "Lawrence T. Wrentz",
    ],
    plot: "A young FBI cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
    src: "https://tse3.mm.bing.net/th?id=OIP.YkYtByL5kRX6rOcXkOTLzAHaK_&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "Forrest Gump",
    year: 1994,
    director: "Robert Zemeckis",
    genre: "Drama, Romance",
    rating: 8.8,
    runtime: 142,
    actors: [
      "Tom Hanks",
      "Robin Wright",
      "Gary Sinise",
      "Sally Field",
      "Mykelti Williamson",
    ],
    plot: "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.",
    src: "https://tse2.mm.bing.net/th?id=OIP.6shvjm1hboxO8iDtu10xCwHaLH&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "The Usual Suspects",
    year: 1995,
    director: "Bryan Singer",
    genre: "Crime, Mystery, Thriller",
    rating: 8.5,
    runtime: 106,
    actors: [
      "Kevin Spacey",
      "Gabriel Byrne",
      "Chazz Palminteri",
      "Stephen Baldwin",
      "Benicio Del Toro",
    ],
    plot: "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a seemingly random police lineup.",
    src: "https://tse2.mm.bing.net/th?id=OIP.mjpV4UfUMUL3gUGCshY5PQHaLH&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "The Lion King",
    year: 1994,
    director: "Roger Allers, Rob Minkoff",
    genre: "Animation, Adventure, Drama",
    rating: 8.5,
    runtime: 88,
    actors: [
      "Matthew Broderick",
      "Jeremy Irons",
      "James Earl Jones",
      "Whoopi Goldberg",
      "Moira Kelly",
    ],
    plot: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.",
    src: "https://tse2.mm.bing.net/th?id=OIP.E7sPXDWU77LUfViUMTIajQHaLH&pid=Api&P=0&h=180",
  },
  {
    id: uuid(),
    title: "The Green Mile",
    year: 1999,
    director: "Frank Darabont",
    genre: "Crime, Drama, Fantasy",
    rating: 8.6,
    runtime: 189,
    actors: [
      "Tom Hanks",
      "Michael Clarke Duncan",
      "David Morse",
      "Bonnie Hunt",
      "James Cromwell",
    ],
    plot: "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape, yet who has a mysterious gift.",
    src: "https://tse2.mm.bing.net/th?id=OIP.CkAGQpX0OPtlJ8F3SFoKQAHaLH&pid=Api&P=0&h=180",
  },
];

const favoriteMovieList = [];

function App() {
  const [data, setData] = useState(moviesData); // Use state to store the movies data
  const [favoriteMovie, setFavoriteMovie] = useState(favoriteMovieList);
  //console.log(data)

  return (
    <div className="App">
      <NavBar />
      <div className="main">
        <SideBar data={data} />
        {/* <HomePage data={data}/>  */}
        <Outlet
          context={{
            data,
            setData,
            favoriteMovie,
            setFavoriteMovie,
          }}
        />
      </div>
    </div>
  );
}

export default App;
